### ISSUE TITLE
update cycpp to allow default values to be defined constants

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#1195]
e.g. in the ``FuelFab``, the following lines
```
  #pragma cyclus var { \
    "doc": "Top-up material stream request preference.", \
    "uilabel": "Top-up Stream Preference", \
    "default": cyclus::kDefaultPref, \
  }
  double topup_pref;
```

result in the following error
```
Traceback (most recent call last):
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 2306, in <module>
    main()
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 2290, in main
    context, superclasses = accumulate_state(canon)   # pass 2
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 861, in accumulate_state
    state.accumulate(statement, sep)
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 713, in accumulate
    filter.transform(statement, sep)
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 475, in transform
    state.var_annotations = self._eval()
  File "/home/gidden/.local/include/cyclus/../../bin/cycpp.py", line 457, in _eval
    annotations = eval(raw, glb, lcl)
  File "<string>", line 1
    { "doc": "Top-up material stream request preference.", "uilabel": "Top-up Stream Preference", "default": cyclus::kDefaultPref, }
                                                                                                                   ^
SyntaxError: invalid syntax
```

This may be difficult, as I'm not sure the current infrastructure supports this type of operation.

**Comment by rwcarlsen** [comment]
All pragma annotations need to be correct python syntax.  So the way you've written it can't work.  But we could come up with some sort of flag to treat a default string text as literal code.

**Comment by gidden** [comment]
Yup, I agree that some additional work will be required to support this.

On Fri, Jul 10, 2015 at 12:10 PM, Robert Carlsen <notifications@github.com>
wrote:

> All pragma annotations need to be correct python syntax. So the way you've
> written it can't work. But we could come up with some sort of flag to treat
> a default string text as literal code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus/issues/1195#issuecomment-120462383>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
@dean-krueger - I think the recent changes to cycpp addressed this... can you confirm?

**Comment by dean-krueger** [comment]
let me check! I'm not sure, though, since what Codex did was allow:

```
#pragma cyclus var { \
...
}
double latitude = 0.0;
```

And what this wants is:

```
#pragma cyclus var { \
"default": kDefaultLatitude
...
}
double latitude;

**Comment by dean-krueger** [comment]
<img width="937" height="126" alt="Image" src="https://github.com/user-attachments/assets/a142e1f2-f1b5-4ee5-8f37-a6b96203084d" />

My suspicions seem to be correct, though I will note we CAN set these to `CY_LARGE_DOUBLE`, so that's interesting. This will likely take some more digging/has to do with JSON or something.

**Comment by gonuke** [comment]
I think your work fixed this in a different way.  Note that this issue was written before the standard allowed initialization in the declaration.  I agree that the syntax you tested in not handled by updates to cycpp, but if we initialize in the declaration - that you did enable, we get essentially the same functionality.

**Comment by gonuke** [comment]
Hmmm... maybe it's not quite the same, but worth cross-referencing.

In places where the default value is a literal, then your fix will allow the default value to be specified in the metadata string as well as in the declaration.

In places where the default value is a constant, then your fix will (?) allow the default value to be specified by that constant in the declaration, but it will still not allow it to be given in the metadata string.

The reason that CY_LARGE_DOUBLE works is that it is defined in the python world as well so it resolves to something in python as well.
