### ISSUE TITLE
cycstub cli produces a stub that doesn't build

### ISSUE THREAD

**Issue by katyhuff** [cyclus/cyclus#1387]
As the title says, the cycstub cli produces a non-building stub. I'm working on tracking this down today, but wanted to create an issue about it. I'll assign myself.

I'm on a clean ubuntu 16.04 vm, using python 3.5 to build the most recent cyclus develop branch. Though the cyclus build throws a bunch of the warnings seen in #1366, it seems to pass all of its tests. 

I create a cycstub test stub thus:

```bash

cyc-user@cyclusbox:~/cyclus$ mkdir teststub
cyc-user@cyclusbox:~/cyclus$ cd teststub/
cyc-user@cyclusbox:~/cyclus/teststub$ cycstub --type facility teststub:testlib:TestFacility
/home/cyc-user/cyclus/install/bin/cyclus
Exception ignored in: 'pymodule.clear_pyagent_refs'
NameError: name 'cyclib' is not defined
cyc-user@cyclusbox:~/cyclus/teststub$ ls
cmake  CMakeLists.txt  example_test_facility.xml  install.py  README.rst  src
```

Please note, the "exception ignored and nameError 'cyclib' seem to me to be related to #1366 and probably are unrelated to the following stub build issue. So, anyway, I build the test stub I've just created, thus:

```bash
cyc-user@cyclusbox:~/cyclus/teststub$ python install.py --clean-build --prefix=../install
```

<details>
<summary>Stub Build Fail</summary>

```bash
cyc-user@cyclusbox:~/cyclus/teststub$ python install.py --clean-build --prefix=../install
/usr/bin/cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success

CMAKE_MODULE_PATH /share/cmake-2.8/Modules;/home/cyc-user/cyclus/teststub/cmake
-- Using /home/cyc-user/cyclus/install as CYCLUS_ROOT_DIR.
-- Dependency Cyclus (DEPS_CYCLUS): 
-- Dependency Library Cyclus (DEPS_LIB_CYCLUS): 
-- Dependency Share Cyclus (DEPS_SHARE_CYCLUS): 
-- Dependency Include Cyclus (DEPS_INCLUDE_CYCLUS): 
-- Found Cyclus Core Headers : /home/cyc-user/cyclus/install/include/cyclus
-- Found Cyclus Core Test Headers : /home/cyc-user/cyclus/install/include/cyclus
-- Found Cyclus Core Shared Data : /home/cyc-user/cyclus/install/share/cyclus
-- Found Cyclus Core Library : /home/cyc-user/cyclus/install/lib/libcyclus.so
-- Found Cyclus Test Libraries : /home/cyc-user/cyclus/install/lib/cyclus/libgtest.so/home/cyc-user/cyclus/install/lib/cyclus/libbaseagentunittests.so
--LD_LIBRARY_PATH: 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
--    HDF5 Root: 
--    HDF5 Include directory: /usr/include/hdf5/serial
--    HDF5 Library directories: /usr/lib/x86_64-linux-gnu/hdf5/serial
--    HDF5 Libraries: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
	COIN Root Dir: 
-- COIN_ROOT_DIR hint is : 
-- Coin multiple library dependency status:
	COIN Include Dir: /usr/include/coin
	COIN CBC: /usr/lib/x86_64-linux-gnu/libCbc.so
	COIN CBC solver: /usr/lib/x86_64-linux-gnu/libCbcSolver.so
	COIN CGL: /usr/lib/x86_64-linux-gnu/libCgl.so
	COIN CLP SOLVER: COIN_CLP_SOLVER_LIBRARY-NOTFOUND
	COIN CLP: /usr/lib/x86_64-linux-gnu/libClp.so
	COIN UTILS: /usr/lib/x86_64-linux-gnu/libCoinUtils.so
	COIN OSI: /usr/lib/x86_64-linux-gnu/libOsi.so
	COIN OSI CBC: /usr/lib/x86_64-linux-gnu/libOsiCbc.so
	COIN OSI CLP: /usr/lib/x86_64-linux-gnu/libOsiClp.so
	COIN ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
	COIN BZ2: /usr/lib/x86_64-linux-gnu/libbz2.so
-- Found COIN: /usr/include/coin  
-- Found COIN Include Dirs: /usr/include/coin
-- Starting construction of build files for agent: test_facility
dstcustomheaders: 
-- Executing /home/cyc-user/cyclus/install/include/cyclus/../../bin/cycpp.py /home/cyc-user/cyclus/teststub/src/test_facility.cc --cpp-path=cpp -o=/home/cyc-user/cyclus/teststub/build/testlib/test_facility.cc --pass3-use-orig -I=:/home/cyc-user/cyclus/install/include/cyclus:/usr/include:/usr/include/hdf5/serial:/usr/include/coin
-- Executing /home/cyc-user/cyclus/install/include/cyclus/../../bin/cycpp.py /home/cyc-user/cyclus/teststub/src/test_facility.h --cpp-path=cpp -o=/home/cyc-user/cyclus/teststub/build/testlib/test_facility.h --pass3-use-orig -I=:/home/cyc-user/cyclus/install/include/cyclus:/usr/include:/usr/include/hdf5/serial:/usr/include/coin
-- Copying /home/cyc-user/cyclus/teststub/src/test_facility_tests.cc to /home/cyc-user/cyclus/teststub/build/testlib/test_facility_tests.cc.
-- Finished construction of build files for agent: test_facility
-- Building agent unit test binary: testlib_unit_tests
-- Using source: ;/home/cyc-user/cyclus/teststub/build/testlib/test_facility.cc;/home/cyc-user/cyclus/teststub/build/testlib/test_facility_tests.cc
-- And test driver: /home/cyc-user/cyclus/install/share/cyclus/cyclus_default_unit_test_driver.cc
-- Configuring done
CMake Warning (dev) at /home/cyc-user/cyclus/install/share/cyclus/cmake/UseCyclus.cmake:265 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target
  "/home/cyc-user/cyclus/teststub/build/testlib/test_facility.cc" of target
  "testlib" does not exist.
Call Stack (most recent call first):
  /home/cyc-user/cyclus/install/share/cyclus/cmake/UseCyclus.cmake:256 (INSTALL_AGENT_LIB_)
  src/CMakeLists.txt:4 (INSTALL_CYCLUS_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/cyc-user/cyclus/install/share/cyclus/cmake/UseCyclus.cmake:265 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target
  "/home/cyc-user/cyclus/teststub/build/testlib/test_facility.h" of target
  "testlib" does not exist.
Call Stack (most recent call first):
  /home/cyc-user/cyclus/install/share/cyclus/cmake/UseCyclus.cmake:256 (INSTALL_AGENT_LIB_)
  src/CMakeLists.txt:4 (INSTALL_CYCLUS_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/cyc-user/cyclus/teststub/build
Scanning dependencies of target testlib
[ 11%] Building CXX object src/CMakeFiles/testlib.dir/__/testlib/test_facility.cc.o
[ 22%] Linking CXX shared library ../lib/cyclus/testlib/libtestlib.so
[ 33%] Built target testlib
Scanning dependencies of target testlib_unit_tests
[ 44%] Building CXX object src/CMakeFiles/testlib_unit_tests.dir/home/cyc-user/cyclus/install/share/cyclus/cyclus_default_unit_test_driver.cc.o
[ 55%] Building CXX object src/CMakeFiles/testlib_unit_tests.dir/__/testlib/test_facility.cc.o
[ 66%] Building CXX object src/CMakeFiles/testlib_unit_tests.dir/__/testlib/test_facility_tests.cc.o
/home/cyc-user/cyclus/teststub/build/testlib/test_facility_tests.cc:10:16: error: ‘TestFacility’ is already declared in this scope
 using testlib::TestFacility;
                ^
src/CMakeFiles/testlib_unit_tests.dir/build.make:125: recipe for target 'src/CMakeFiles/testlib_unit_tests.dir/__/testlib/test_facility_tests.cc.o' failed
make[2]: *** [src/CMakeFiles/testlib_unit_tests.dir/__/testlib/test_facility_tests.cc.o] Error 1
CMakeFiles/Makefile2:156: recipe for target 'src/CMakeFiles/testlib_unit_tests.dir/all' failed
make[1]: *** [src/CMakeFiles/testlib_unit_tests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 137, in <module>
    main()
  File "install.py", line 134, in main
    install(args)
  File "install.py", line 68, in install
    shell=(os.name == 'nt'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
cyc-user@cyclusbox:~/cyclus/teststub$ 
```

</details>
<br/>

Relatedly, the docs are out of date in https://github.com/cyclus/cyclus/blob/develop/stubs/README.rst . I'll create a separate issue for that.

**Comment by katyhuff** [comment]
Of course, this is because I called it testfacility... closing in favor of a fix in the docs.
