### ISSUE TITLE
nosetests failing with numpy 1.12.0+

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1411]
This is apparently a know issue, (according to google) but I can't understand how to fix it.

I was hoping one of you (@scopatz @FlanFlanagan @katyhuff ) had a better understanding

```
======================================================================
ERROR: Failure: TypeError (only integer scalar arrays can be converted to a scalar index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
    for test in g():
  File "/Users/mouginot/work/app/cyclus/cyclus/tests/test_lotka_volterra.py", line 41, in test_predator_only
    series = agent_time_series([prey, pred])
  File "/Users/mouginot/work/app/cyclus/cyclus/tests/helper.py", line 149, in agent_time_series
    entries[name][agent_entry[idx]['EnterTime'][0]] += 1
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by scopatz** [comment]
I think that this is because idx is a list or similar.  (I thought I had put in a PR to fix this...but maybe that was to cymetric?)  I think the fix is to use `idx[0]`. It is a len-1 array as a recall.

**Comment by bam241** [comment]
@scopatz you were right, and also the [0] at the end was not required
` entries[name][agent_entry[idx]['EnterTime'][0]] += 1`
should have been
` entries[name][agent_entry[idx[0]]['EnterTime']] += 1`

I include this in the #1410 PR

**Comment by bam241** [comment]
this has been fixed! closing.
