### ISSUE TITLE
MacOS install issue

### ISSUE THREAD

**Issue by gwenchee** [cyclus/cyclus#1433]
I am installing Cyclus from conda python with Cyclus build deps installed. I am installing from the latest master. I am not sure if i am using Clang or gcc compiler and how to check. 

The error is: 

```
[ 52%] Linking CXX executable ../bin/cyclus
Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) in cyclus.cc.o
  "boost::program_options::invalid_option_value::invalid_option_value(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long) in cyclus.cc.o
  "boost::program_options::error_with_option_name::error_with_option_name(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in cyclus.cc.o
  "boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>)", referenced from:
      boost::program_options::basic_command_line_parser<char>::extra_parser(boost::function1<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>) in cyclus.cc.o
  "boost::program_options::detail::cmdline::cmdline(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in cyclus.cc.o
  "boost::program_options::validate(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)", referenced from:
      boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const in cyclus.cc.o
  "boost::program_options::operator<<(std::basic_ostream<char, std::char_traits<char> >&, boost::program_options::options_description const&)", referenced from:
      _main in cyclus.cc.o
      ParseCliArgs(ArgInfo*, int, char**) in cyclus.cc.o
      EarlyExitArgs(ArgInfo const&) in cyclus.cc.o
  "boost::program_options::abstract_variables_map::operator[](std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      boost::program_options::variables_map::operator[](std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in cyclus.cc.o
  "boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      vtable for boost::program_options::invalid_option_value in cyclus.cc.o
      vtable for boost::program_options::validation_error in cyclus.cc.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in cyclus.cc.o
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in cyclus.cc.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> > in cyclus.cc.o
      vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> in cyclus.cc.o
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<unsigned int, char> in cyclus.cc.o
      vtable for boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> in cyclus.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cyclus] Error 1
make[1]: *** [cli/CMakeFiles/cyclus_cli.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 214, in <module>
    main()
  File "install.py", line 211, in main
    install_cyclus(args)
  File "install.py", line 107, in install_cyclus
    shell=(os.name == 'nt'))
  File "/Users/gwendolynchee/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

```

**Comment by scopatz** [comment]
Thanks for reporting, @gwenchee. Try updating boost.

**Comment by gwenchee** [comment]
Thanks for the quick response! I already have the latest version of boost (version 1.65.1).

**Comment by scopatz** [comment]
Did you perform a fully clean build (ie remove the build/ dir).  Sometimes these issues happen when new versions come out.

**Comment by bam241** [comment]
" I am not sure if i am using Clang or gcc compiler and how to check."
@gwenchee 
this should be detailed in the first 3 line of output of the installation script:
```
/opt/local/bin/cmake
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
```

**Comment by gwenchee** [comment]
Hello all, 
I managed to get cyclus and the unit tests to run. 
I used your suggestion @scopatz of clean building and used gcc instead of clang to compile. 
This is what I put into the terminal to get cyclus to run: 
python install.py -DCMAKE_C_COMPILER=/usr/bin/gcc --clean-build

**Comment by scopatz** [comment]
Great! Glad you got it working!
