### ISSUE TITLE
installation issue "cannot create directory: /cyclus"

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1446]
Second time I run into this issue.

First Emma, and now Eric a graduate student working with us.
Eric is using Ubuntu 16.04 virtual machine with python2.

```
CMake Error at cyclus/cmake_install.cmake:50 (file):
  file cannot create directory: /cyclus.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  cmake_install.cmake:74 (include)
  


Makefile:83: recipe for target 'install' failed
make: *** [install] Error 1
Traceback (most recent call last):
  File "install.py", line 214, in <module>
    main()
  File "install.py", line 211, in main
    install_cyclus(args)
  File "install.py", line 115, in install_cyclus
    shell=(os.name == 'nt'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2
```

**Comment by bam241** [comment]
switching to python3 fixes the issue.

**Comment by scopatz** [comment]
Can you post the full error message in a gist please?

**Comment by bam241** [comment]
unfortunately I don't have it. 

I'll try to reproduce it with a docker container.

**Comment by bam241** [comment]
docker will not work with a the default ubuntu container because default user is root, so we don't run into this privilege issue...

I'll come with an shareable example asap.
