### ISSUE TITLE
Cyclus python binding for trade.request.requester issue

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclus#1462]
Calling trade.request.requester (or trade.request.requester()) results in a segmentation fault. This issue is in casting the requester I think. Python attempts to call agent_to_py. However, in C++ the requester of a request is actually a trader and not an agent. 

Is this by design @scopatz ? (not the bug, the change from trader to agent)

**Comment by scopatz** [comment]
Thanks for reporting @flanflanagan. Can you please provide the backtrace?

**Comment by FlanFlanagan** [comment]
```
#0  0x00007fffd5615798 in construction vtable for cyclus::Agent-in-CyclusFacilityShim ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#1  0x00007fffe044f92c in __pyx_f_6cyclus_3lib_agent_to_py(cyclus::Agent*, _object*) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/lib.so
#2  0x00007fffdc7dec32 in __pyx_pf_6cyclus_10typesystem_16_MaterialRequest_9requester___get__(__pyx_obj_6cyclus_10typesystem__MaterialRequest*) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/typesystem.so
#3  0x00007fffdc7deb43 in __pyx_pw_6cyclus_10typesystem_16_MaterialRequest_9requester_1__get__(_object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/typesystem.so
#4  0x00007fffdc804e42 in __pyx_getprop_6cyclus_10typesystem_16_MaterialRequest_requester(_object*, void*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/typesystem.so
#5  0x00007fffedd1851c in _PyObject_GenericGetAttrWithDict (obj=0x7fffd5298748, 
    name=0x7fffdd0d2630, dict=0x0) at Objects/object.c:1059
#6  0x00007fffeddacd2a in PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:2793
#7  0x00007fffd53d6e8d in __Pyx_PyFunction_FastCallNoKw(PyCodeObject*, _object**, long, _object*) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#8  0x00007fffd53d707b in __Pyx_PyFunction_FastCallDict(_object*, _object**, int, _object*) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#9  0x00007fffd5394a2e in CyclusFacilityShim::GetMatlTrades(std::vector<cyclus::Trade<cyclus::Material>, std::allocator<cyclus::Trade<cyclus::Material> > > const&, std::vector<std::pair<cyclus::Trade<cyclus::Material>, boost::shared_ptr<cyclus::Material> >, std::allocator<std::pair<cyclus::Trade<cyclus::Material>, boost::shared_ptr<cyclus::Material> > > >&) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#10 0x00007fffed49d719 in cyclus::ExchangeManager<cyclus::Material>::Execute() ()
   from /home/robert/miniconda3/bin/../lib/libcyclus.so
#11 0x00007fffed48864c in cyclus::Timer::DoResEx(cyclus::ExchangeManager<cyclus::Material>*, cyclus::ExchangeManager<cyclus::Product>*) () from /home/robert/miniconda3/bin/../lib/libcyclus.so
#12 0x00007fffed4889bc in cyclus::Timer::RunSim() ()
   from /home/robert/miniconda3/bin/../lib/libcyclus.so
#13 0x0000000000412bd8 in main ()

```

**Comment by FlanFlanagan** [comment]
Currently a fix is in the works for this.

**Comment by FlanFlanagan** [comment]
This is fixed in #1466 , but is not in the conda release of cyclus yet.
