### ISSUE TITLE
Stopping a cyclus run 

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1463]
Since the python binding, I am not able to stop a cyclus simulation using `CTRL +C`.

Am I the only one?
Ss it normal ?
Can we fix it ?

Sorry for being so long to report it :(

**Comment by scopatz** [comment]
I believe that I can stop it with crtl+c, have you tried crtl+z?

**Comment by FlanFlanagan** [comment]
Note ctrl+z only sleeps the operation. It is still stored on the machine. 

I know this happens with Python modules because you only kill the process in the module and not the full cyclus run. Not sure why it happens with C++ modules.

**Comment by bam241** [comment]
yes after the ctrl+z I have to kill the process manually :)

**Comment by scopatz** [comment]
Hmmm maybe Python is eating the KeyboardInterrupt...

**Comment by scopatz** [comment]
@bam241 are you seeing any output at all?

**Comment by scopatz** [comment]
Potential fix in #1467

**Comment by bam241** [comment]
@scopatz 
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 995, in _handle_fromlist
KeyboardInterrupt
Exception ignored in: 'eventhooks.eventloophook'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 995, in _handle_fromlist
KeyboardInterrupt
```

**Comment by bam241** [comment]
I have a cyclus simulation running I try your fix as soon as it finishes

**Comment by scopatz** [comment]
yeah I think that PR should fix it, given the traceback

**Comment by scopatz** [comment]
@bam241 can you provide a minimal input file that produces the issue that you are seeing?
