### ISSUE TITLE
Python agent issue with Resource.append

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclus#1465]
Traceback (most recent call last):
  File "agents.pyx", line 945, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 618, in cyclus.typesystem._ResBufMaterial.pop_all_res
  File "typesystem.pyx", line 588, in cyclus.typesystem._ResBufMaterial.pop_n_res
AttributeError: 'Resource' object has no attribute 'append'

This error occured at the end of a run using the in development peddler archetype. 

@scopatz

**Comment by scopatz** [comment]
OK looking into it now.

**Comment by scopatz** [comment]
Hmm When I run peddler on the `cast_fix` branch, it works just fine.  Have you added something to peddler that you haven't pushed up?

**Comment by scopatz** [comment]
This is a legit error, though.  I think I see what the problem is. Fix incoming.

**Comment by FlanFlanagan** [comment]
You'll need to be on the most recent version of Peddler to see it. I think it comes from inventory in the reactor?

**Comment by scopatz** [comment]
I am on the most recent version.

**Comment by scopatz** [comment]
Did the fix in #1466 work?

**Comment by FlanFlanagan** [comment]
```
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got list)
Exception ignored in: 'CyclusFacilityShim.SnapshotInv'
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got list)
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got list)
Exception ignored in: 'CyclusFacilityShim.SnapshotInv'
Traceback (most recent call last):
  File "agents.pyx", line 946, in cyclus.agents._Agent.snapshot_inv
  File "typesystem.pyx", line 626, in cyclus.typesystem._ResBufMaterial.push_many
TypeError: Argument 'r' has incorrect type (expected cyclus.typesystem._Material, got list)

```

**Comment by FlanFlanagan** [comment]
It would appear material is not the issue?

Are you use ergs/peddler, or flanflanagan/peddler?

**Comment by scopatz** [comment]
I was using ergs, rather than your fork.  I'll switch.  Also, that is a new error :)

**Comment by scopatz** [comment]
great, thanks!
