### ISSUE TITLE
Making Cyclus compatible with Cyder 

### ISSUE THREAD

**Issue by gwenchee** [cyclus/cyclus#1469]
I am currently trying to connect cyder with the current version of Cyclus. One of the issues i'm realizing is that there are functions that are used in Cyder that no longer exist in Cyclus such as: Event.h , EventBackend.h , EventManager.h etc. What i have done is that i found these functions in a 2013 forked repository of Cyclus (https://github.com/Sjenitzer/cyclus) and have been reinstating them into the cyder-compatibility branch of my forked cyclus (https://github.com/gwenchee/cyclus/tree/cyder-compatibility). 

I tried installing Cyclus with the file additions and am running into an error where it is saying this: 
``` 
[  1%] Building CXX object src/CMakeFiles/cyclus.dir/Event.cc.o
In file included from /home/gtw2/cyclus/src/IntrusiveBase.h:8:0,
                 from /home/gtw2/cyclus/src/Event.h:5,
                 from /home/gtw2/cyclus/src/Event.cc:3:
/home/gtw2/cyclus/src/exchange_translator.h: In function ‘void cyclus::TranslateCapacities(typename T::Ptr, const std::set<cyclus::CapacityConstraint<T> >&, cyclus::ExchangeNode::Ptr, const cyclus::Arc&, const cyclus::ExchangeTranslationContext<T>&)’:
/home/gtw2/cyclus/src/exchange_translator.h:287:10: error: ‘LEV_DEBUG1’ is not a member of ‘cyclus’
     CLOG(cyclus::LEV_DEBUG1) << "Additing unit capacity: "
          ^
/home/gtw2/cyclus/src/logger.h:33:5: note: in definition of macro ‘CLOG’
 if (level > Logger::ReportLevel()) ; \
     ^
/home/gtw2/cyclus/src/exchange_translator.h:287:10: note: suggested alternative:
     CLOG(cyclus::LEV_DEBUG1) << "Additing unit capacity: "
          ^
/home/gtw2/cyclus/src/logger.h:33:5: note: in definition of macro ‘CLOG’
 if (level > Logger::ReportLevel()) ; \
     ^
In file included from /home/gtw2/cyclus/src/IntrusiveBase.h:8:0,
                 from /home/gtw2/cyclus/src/Event.h:5,
                 from /home/gtw2/cyclus/src/Event.cc:3:
/home/gtw2/cyclus/src/logger.h:59:16: note:   ‘LEV_DEBUG1’
                LEV_DEBUG1, //!< debugging information - least verbose
                ^
In file included from /home/gtw2/cyclus/src/IntrusiveBase.h:8:0,
                 from /home/gtw2/cyclus/src/Event.h:5,
                 from /home/gtw2/cyclus/src/Event.cc:3:
/home/gtw2/cyclus/src/exchange_translator.h:287:10: error: ‘LEV_DEBUG1’ is not a member of ‘cyclus’
     CLOG(cyclus::LEV_DEBUG1) << "Additing unit capacity: "
          ^
/home/gtw2/cyclus/src/logger.h:34:19: note: in definition of macro ‘CLOG’
 else Logger().Get(level, "core")
                   ^
/home/gtw2/cyclus/src/exchange_translator.h:287:10: note: suggested alternative:
     CLOG(cyclus::LEV_DEBUG1) << "Additing unit capacity: "
          ^
/home/gtw2/cyclus/src/logger.h:34:19: note: in definition of macro ‘CLOG’
 else Logger().Get(level, "core")
                   ^
In file included from /home/gtw2/cyclus/src/IntrusiveBase.h:8:0,
                 from /home/gtw2/cyclus/src/Event.h:5,
                 from /home/gtw2/cyclus/src/Event.cc:3:
/home/gtw2/cyclus/src/logger.h:59:16: note:   ‘LEV_DEBUG1’
                LEV_DEBUG1, //!< debugging information - least verbose
                ^
src/CMakeFiles/cyclus.dir/build.make:118: recipe for target 'src/CMakeFiles/cyclus.dir/Event.cc.o' failed
make[2]: *** [src/CMakeFiles/cyclus.dir/Event.cc.o] Error 1
CMakeFiles/Makefile2:1070: recipe for target 'src/CMakeFiles/cyclus.dir/all' failed
make[1]: *** [src/CMakeFiles/cyclus.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 223, in <module>
    main()
  File "install.py", line 219, in main
    install_cyclus(args)
  File "install.py", line 106, in install_cyclus
    shell=(os.name == 'nt'))
  File "/home/gtw2/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
``` 
Does anyone have any ideas on how i can resolve this error?

**Comment by gwenchee** [comment]
Thanks @scopatz , I will try that instead.

**Comment by gwenchee** [comment]
What would the current api be for IsoVector? I am looking through the git logs, but I can't find any reference to what it might have been changed or incorporated with.

**Comment by scopatz** [comment]
I think IsoVector was renamed to CompMap.  It is basically a `map<int, double>`

**Comment by gwenchee** [comment]
I was under the impression that the CompMap function was renamed comp_math? Because there is no longer a CompMap function in the src folder

**Comment by scopatz** [comment]
CompMap is a container for mapping nuclides to mass or atom fractions, like what I recall IsoVector was.  CompMap, like IsoVector, is just a typedef (and not a function), see line 17 of composition.h.   comp_math provides some floating point precision maximizing routines for compositions and performs operations on top on CompMaps

**Comment by gwenchee** [comment]
Ah i see. IsoVector was a typedef declared with the IsoVector.h and IsoVector.cc file. Since the files do not exist anymore, would this be the right way to correct the issue? 

1) include composition.h in the header file that included IsoVector.h 
2) Use CompMap each time in place of IsoVector

**Comment by scopatz** [comment]
Yep! That's right
