### ISSUE TITLE
Python Module issue with ts.MapStringVectorDouble

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclus#1476]
There is some sort of issue when using this typesystem object in a python module. 

error and backtrace

`AttributeError: 'list' object has no attribute 'encode'
Exception ignored in: 'cyclus.typesystem.str_py_to_cpp'
AttributeError: 'list' object has no attribute 'encode'
XPath error : Invalid expression
terminate called after throwing an instance of 'xmlpp::exception'
  what():  Invalid XPath: 

Thread 1 "cyclus" received signal SIGABRT, Aborted.
0x00007fffe9a13428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fffe9a13428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffe9a1502a in __GI_abort () at abort.c:89
#2  0x00007fffea01dbb5 in __gnu_cxx::__verbose_terminate_handler() () from /home/robert/miniconda3/bin/../lib/libstdc++.so.6
#3  0x00007fffea01bd56 in ?? () from /home/robert/miniconda3/bin/../lib/libstdc++.so.6
#4  0x00007fffea01bd83 in std::terminate() () from /home/robert/miniconda3/bin/../lib/libstdc++.so.6
#5  0x00007fffea01bfa2 in __cxa_throw () from /home/robert/miniconda3/bin/../lib/libstdc++.so.6
#6  0x00007ffff48febf2 in xmlpp::find_impl(_xmlXPathContext*, Glib::ustring const&) () from /home/robert/miniconda3/bin/../lib/libxml++-2.6.so.2
#7  0x00007ffff48fef1a in xmlpp::Node::find(Glib::ustring const&) const () from /home/robert/miniconda3/bin/../lib/libxml++-2.6.so.2
#8  0x00007fffed2a52b3 in cyclus::InfileTree::GetEngineFromQuery(std::string, int) () from /home/robert/miniconda3/bin/../lib/libcyclus.so
#9  0x00007fffed2a4990 in cyclus::InfileTree::SubTree(std::string, int) () from /home/robert/miniconda3/bin/../lib/libcyclus.so
#10 0x00007fffe045fb3b in __pyx_pf_6cyclus_3lib_11_InfileTree_12subtree(__pyx_obj_6cyclus_3lib__InfileTree*, _object*, int) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/lib.so
#11 0x00007fffe045f817 in __pyx_pw_6cyclus_3lib_11_InfileTree_13subtree(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/lib.so
#12 0x00007fffedd17199 in PyCFunction_Call (func=0x7fffcafabe58, args=0x7fffcaf81448, kwds=<optimized out>) at Objects/methodobject.c:98
#13 0x00007fffd53e6bbf in __Pyx_PyObject_Call(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#14 0x00007fffd53b6a4d in __pyx_pf_6cyclus_6agents_6_Agent_14_read_from_infile(__pyx_obj_6cyclus_6agents__Agent*, _object*, _object*, _object*, _object*, _object*, _object*) ()
   from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#15 0x00007fffd53b5f27 in __pyx_pw_6cyclus_6agents_6_Agent_15_read_from_infile(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#16 0x00007fffedd17199 in PyCFunction_Call (func=0x7fffcaf34c60, args=0x7fffd52d3908, kwds=<optimized out>) at Objects/methodobject.c:98
#17 0x00007fffd53e6bbf in __Pyx_PyObject_Call(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#18 0x00007fffd53b2890 in __pyx_pf_6cyclus_6agents_6_Agent_10infile_to_db(__pyx_obj_6cyclus_6agents__Agent*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#19 0x00007fffd53b0a61 in __pyx_pw_6cyclus_6agents_6_Agent_11infile_to_db(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#20 0x00007fffedd17199 in PyCFunction_Call (func=0x7fffcaf34c18, args=0x7fffcaff1348, kwds=<optimized out>) at Objects/methodobject.c:98
#21 0x00007fffd53e6bbf in __Pyx_PyObject_Call(_object*, _object*, _object*) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#22 0x00007fffd538e313 in CyclusInstitutionShim::InfileToDb(cyclus::InfileTree*, cyclus::DbInit) () from /home/robert/.local/lib/python3.5/site-packages/cyclus/agents.so
#23 0x00007fffed4af962 in cyclus::XMLFileLoader::LoadInitialAgents() () from /home/robert/miniconda3/bin/../lib/libcyclus.so
#24 0x00007fffed4af2cd in cyclus::XMLFileLoader::LoadSim() () from /home/robert/miniconda3/bin/../lib/libcyclus.so
#25 0x0000000000412c95 in main ()
`

To reproduce this you will need 
A branch of cyclus from my fork called 'time series'
A branch of d3ploy from my fork called 'region'

I'll attach the input file to this issue shortly.

**Comment by FlanFlanagan** [comment]
@scopatz 
[test.txt](https://github.com/cyclus/cyclus/files/2103211/test.txt)

github does not support .xml attachments? Anyway. it's also on the branch.
