### ISSUE TITLE
Cmake and Index Error & Cmake Warning

### ISSUE THREAD

**Issue by negatron1** [cyclus/cyclus#1547]
Hi everyone, hope doing well!
I try to install Cyclus but ı gave the same error for both ways (cmake and install.py installation).
The error is like below and how can ı fix that? Could you help me, please?

CMake Warning at CMakeLists.txt:391 (MESSAGE):
  Unable to read current core version, falling back to previous version.
  Core version will be set to -1

-- core version ($CYCLUS_CORE_VERSION) set to: -1
-- Found '/home/positron/cyclus-master/share/cyclus_nuc_data.h5'
-- default_allow_milps: false
Traceback (most recent call last):
  File "/home/positron/cyclus-master/src/hdf5_back_gen.py", line 2859, in <module>
    main()
  File "/home/positron/cyclus-master/src/hdf5_back_gen.py", line 2852, in main
    setup()
  File "/home/positron/cyclus-master/src/hdf5_back_gen.py", line 2793, in setup
    DB_TO_VL[db] = row[8]
IndexError: tuple index out of range
CMake Error at src/CMakeLists.txt:37 (message):
  Process hdf5_back_gen.py 'VAL_TO_BUF_H' failed, result = '1'

-- Configuring incomplete, errors occurred!
See also "/home/positron/cyclus-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/positron/cyclus-master/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "http://install.py", line 223, in <module>
    main()
  File "http://install.py", line 219, in main
    install_cyclus(args)
  File "http://install.py", line 93, in install_cyclus
    rtn = subprocess.check_call(cmake_cmd, cwd=http://args.build_dir,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/positron/cyclus-master', '-DCMAKE_INSTALL_PREFIX=/home/positron/.local', '-DDEFAULT_ALLOW_MILPS=FALSE']' returned non-zero exit status 1.

**Comment by bam241** [comment]
hi Have you been able to solve this ?
If so do you recall how ?

(Sorry I was not able to help you sooner was of the network for few days...)

**Comment by negatron1** [comment]
Not at all.
I try to install into older version of Ubuntu and ı will inform you when ı get a solution or not, thank you.
