### ISSUE TITLE
CoinCBC version issue

### ISSUE THREAD

**Issue by negatron1** [cyclus/cyclus#1548]
Hİ again!
I try to install cyclus onto Ubuntu 20.04 release but I faced new problem CoinCBC issue. I sought to find the source of the problem and ı found that CoinCBC is allowed up to version 2.9 in file whic is under the src//src/OsiCbcSolverInterface.hpp. But ı don't know how to deal with it. Is there anyone to help me? Thanks.

-- Build files have been written to: /home/electron/cyclus/build
[  0%] Built target ReplicatePythonSourceTree
[  1%] Building CXX object src/CMakeFiles/cyclus.dir/solver_factory.cc.o
In file included from /home/electron/cyclus/src/solver_factory.cc:6:
/home/electron/cyclus/src/OsiCbcSolverInterface.hpp:17:2: error: #error "Cyclus cannot yet handle your version of CoinCBC. Please open an issue with your CoinCBC version."
   17 | #error "Cyclus cannot yet handle your version of CoinCBC. Please open an issue with your CoinCBC version."
      |  ^~~~~
make[2]: *** [src/CMakeFiles/cyclus.dir/build.make:697: src/CMakeFiles/cyclus.dir/solver_factory.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1186: src/CMakeFiles/cyclus.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Traceback (most recent call last):
  File "http://install.py", line 223, in <module>
    main()
  File "http://install.py", line 219, in main
    install_cyclus(args)
  File "http://install.py", line 105, in install_cyclus
    rtn = subprocess.check_call(make_cmd, cwd=http://args.build_dir,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

**Comment by bam241** [comment]
HI, sorry I was not able to reply sooner.

do you know which version of CoinCBC you are using ?

**Comment by negatron1** [comment]
Hi, No ı don't know but ı try to install version 2.9 from git ı took error from the same file when it was compiling.
