### ISSUE TITLE
Install Failure with Ubunutu VM on WIndows

### ISSUE THREAD

**Issue by DanJack1987** [cyclus/cyclus#1577]
after installing all dependencies it crashed out at this step. 

CMake Error at share/CMakeLists.txt:25 (message):
  Process dbtypes_gen.py failed, res_var = 'No such file or directory'

-- Configuring incomplete, errors occurred!
See also "/home/daniel/cyclus/build/CMakeFiles/CMakeOutput.log".
See also "/home/daniel/cyclus/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "install.py", line 223, in <module>
    main()
  File "install.py", line 219, in main
    install_cyclus(args)
  File "install.py", line 93, in install_cyclus
    rtn = subprocess.check_call(cmake_cmd, cwd=args.build_dir,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/daniel/cyclus', '-DCMAKE_INSTALL_PREFIX=/home/daniel/.local', '-DDEFAULT_ALLOW_MILPS=FALSE']' returned non-zero exit status 1.

**Comment by DanJack1987** [comment]
installing python is python3

sudo apt install python-is-python3

Solved this and other problems so far installation is progressed past this point.
