### ISSUE TITLE
Unable to complete installation Ubunutu VM on windows. 

### ISSUE THREAD

**Issue by DanJack1987** [cyclus/cyclus#1578]
100%] Built target py_agents_
Install the project...
-- Install configuration: ""
-- Installing: /home/daniel/.local/share/cyclus/stubs/CMakeLists.txt
-- Installing: /home/daniel/.local/share/cyclus/stubs/example_facility.xml
-- Installing: /home/daniel/.local/share/cyclus/stubs/example_inst.xml
-- Installing: /home/daniel/.local/share/cyclus/stubs/example_region.xml
-- Installing: /home/daniel/.local/share/cyclus/stubs/install.py
-- Installing: /home/daniel/.local/share/cyclus/stubs/README.rst
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/CMakeLists.txt
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_facility.h
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_facility.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_facility_tests.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_inst.h
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_inst.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_inst_tests.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_region.h
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_region.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_region_tests.cc
-- Installing: /home/daniel/.local/share/cyclus/stubs/src/stub_unit_test_driver.cc
############### Begin Python Install ###############
-- Python installer:
  PYTHON_EXECUTABLE: /usr/bin/python
  CYCLUS_CORE_VERSION: 1.5.5-57-gc1910b90
  CMAKE_INSTALL_PREFIX: /home/daniel/.local
  CMAKE_CURRENT_BINARY_DIR: /home/daniel/cyclus/build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
CMake Error at cmake/SetupPyInstall.cmake:17 (message):
  Process setup.py install failed, res_var = '1'
Call Stack (most recent call first):
  cmake_install.cmake:68 (include)

make: *** [Makefile:140: install] Error 1
Traceback (most recent call last):
  File "install.py", line 223, in <module>
    main()
  File "install.py", line 219, in main
    install_cyclus(args)
  File "install.py", line 113, in install_cyclus
    rtn = subprocess.check_call(make_cmd, cwd=args.build_dir,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2.

**Comment by DanJack1987** [comment]
Resolved by 
sudo apt install python3-pip
pip install setuptools
